# Generated by Django 5.1 on 2026-03-26 05:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('average_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('dividend_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Annual dividend per share', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
    ]
