# Generated by Django 5.1 on 2026-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Stock beta from FMP', max_digits=8, null=True),
        ),
    ]
