# Generated by Django 5.1 on 2026-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Latest price from FMP', max_digits=12, null=True),
        ),
    ]
